# Generated by Django 3.2.8 on 2022-10-01 11:46

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20221001_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.expressions.Case, related_name='comment', to='blog.blog'),
        ),
    ]
