# Generated by Django 3.2.8 on 2022-10-16 14:01

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20221001_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cover_image',
            field=models.ImageField(default='cover.jpg', upload_to='cover_images'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.expressions.Case, related_name='comments', to='blog.blog'),
        ),
    ]
