# Generated by Django 3.2.8 on 2022-10-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20221016_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_image',
            field=models.ImageField(default='cover.jpg', null=True, upload_to='cover_images'),
        ),
    ]
