# Generated by Django 3.2.8 on 2022-10-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_image',
            field=models.ImageField(default='cover.jpg', upload_to='cover_images'),
        ),
    ]
