# Generated by Django 3.2.8 on 2022-11-04 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ('-date_created',)},
        ),
    ]
