# Generated by Django 3.2.8 on 2022-11-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20221104_1019'),
        ('blog', '0012_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_tags',
            field=models.ManyToManyField(related_name='blog_tags', to='accounts.Tag'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
