# Generated by Django 3.2.8 on 2022-11-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20221112_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_image',
            field=models.ImageField(default='cover.jpg', upload_to=''),
        ),
    ]
